config/routes.rb
Rails.application.routes.draw do

  get "/hosts/:id/snapshot", to: 'hosts#snapshot', as: 'snapshot'
  get '/hosts/:id/replace_instance', to: 'hosts#replace_instance', as: 'replace'
  get '/hosts/:id/reboot', to: 'hosts#reboot', as: 'reboot'

  resources :instance_security_group_mappings
  resources :aws_security_group_tags
  resources :aws_security_group_ranges
  resources :aws_security_group_pairs
  resources :aws_security_group_egresses
  resources :aws_security_group_ingresses
  resources :aws_security_groups
  resources :aws_route_table_propogates
  resources :aws_route_table_associations
  resources :aws_route_table_tags
  resources :aws_route_table_routes
  resources :aws_route_tables
  resources :aws_network_acl_tags
  resources :aws_network_acl_entries
  resources :aws_network_acls
  resources :aws_key_pairs
  resources :aws_internet_gateway_tags
  resources :aws_internet_gateways
  resources :aws_dhcp_option_attributes
  resources :aws_dhcp_options
  resources :aws_elastic_ips
  resources :aws_account_attributes
  resources :checkpoint_frequencies
  resources :sysids
  resources :ebs_snapshot_tags
  resources :ebs_snapshots
  resources :ebs_volumes
  resources :ebs_volume_tags
  resources :instance_eni_tags
  resources :instance_eni_mappings
  resources :instance_tags
  resources :instance_block_device_mappings
  resources :aws_subnets
  resources :aws_vpc_tags
  resources :aws_vpcs
  resources :instance_enis
  resources :instances
  resources :host_states
  resources :hosts
  resources :aws_azs
  resources :aws_regions
  resources :environments

  resources :aws_accounts

  resources :indices

  root to: 'indices#index', :as => "root"

end

app/models/aws_subnet.rb
class AwsSubnet < ActiveRecord::Base
  belongs_to :aws_vpc, primary_key: 'vpc_id', foreign_key: 'vpc_id'
  belongs_to :aws_az, primary_key: 'availability_zone', foreign_key: 'name'
  validates :subnet_id, :state, :vpc_id, :cidr_block, :available_ip_address_count, :availability_zone, presence: true


  def self.update_subnets
    AwsAccount.all.each do |account|
      AwsRegion.all.each do |aws_region |
        creds = Aws::Credentials.new(account.access_key_id, account.secrete_access_key)
        ec2 = Aws::EC2::Client.new(region: aws_region.name, credentials: creds, http_proxy: PROXY)
        ec2.describe_subnets.subnets.each do |subnet|
          saved_subnet = AwsSubnet.where(subnet_id: subnet.subnet_id).first_or_initialize
          saved_subnet.state = subnet.state
          saved_subnet.vpc_id = subnet.vpc_id
          saved_subnet.cidr_block = subnet.cidr_block
          saved_subnet.available_ip_address_count = subnet.available_ip_address_count
          saved_subnet.availability_zone = subnet.availability_zone
          saved_subnet.default_for_az = subnet.default_for_az
          saved_subnet.map_public_ip_on_launch = subnet.map_public_ip_on_launch
          saved_subnet.save
 	  puts saved_subnet.errors.messages
      end
      end
    end
  end
end

app/controllers/aws_subnets_controller.rb
class AwsSubnetsController < ApplicationController
  before_action :set_aws_subnet, only: [:show, :edit, :update, :destroy]

  # GET /aws_subnets
  # GET /aws_subnets.json
  def index
    @aws_subnets = AwsSubnet.all
  end

  # GET /aws_subnets/1
  # GET /aws_subnets/1.json
  def show
  end

  # GET /aws_subnets/new
  def new
    @aws_subnet = AwsSubnet.new
  end

  # GET /aws_subnets/1/edit
  def edit
  end

  # POST /aws_subnets
  # POST /aws_subnets.json
  def create
    @aws_subnet = AwsSubnet.new(aws_subnet_params)

    respond_to do |format|
      if @aws_subnet.save
        format.html { redirect_to @aws_subnet, notice: 'Aws subnet was successfully created.' }
        format.json { render :show, status: :created, location: @aws_subnet }
      else
        format.html { render :new }
        format.json { render json: @aws_subnet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aws_subnets/1
  # PATCH/PUT /aws_subnets/1.json
  def update
    respond_to do |format|
      if @aws_subnet.update(aws_subnet_params)
        format.html { redirect_to @aws_subnet, notice: 'Aws subnet was successfully updated.' }
        format.json { render :show, status: :ok, location: @aws_subnet }
      else
        format.html { render :edit }
        format.json { render json: @aws_subnet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aws_subnets/1
  # DELETE /aws_subnets/1.json
  def destroy
    @aws_subnet.destroy
    respond_to do |format|
      format.html { redirect_to aws_subnets_url, notice: 'Aws subnet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aws_subnet
      @aws_subnet = AwsSubnet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aws_subnet_params
      params.require(:aws_subnet).permit(:subnet_id, :state, :vpc_id, :cidr_block, :available_ip_address_count, :availability_zone, :default_for_az, :map_public_ip_on_launch)
    end
end

app/helpers/aws_subnets_helper.rb
module AwsSubnetsHelper
end

app/views/aws_subnets/_form.html.erb
<%= form_for(@aws_subnet) do |f| %>
  <% if @aws_subnet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aws_subnet.errors.count, "error") %> prohibited this aws_subnet from being saved:</h2>

      <ul>
      <% @aws_subnet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subnet_id %><br>
    <%= f.text_field :subnet_id %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :vpc_id %><br>
    <%= f.text_field :vpc_id %>
  </div>
  <div class="field">
    <%= f.label :cidr_block %><br>
    <%= f.text_field :cidr_block %>
  </div>
  <div class="field">
    <%= f.label :available_ip_address_count %><br>
    <%= f.number_field :available_ip_address_count %>
  </div>
  <div class="field">
    <%= f.label :availability_zone %><br>
    <%= f.text_field :availability_zone %>
  </div>
  <div class="field">
    <%= f.label :default_for_az %><br>
    <%= f.check_box :default_for_az %>
  </div>
  <div class="field">
    <%= f.label :map_public_ip_on_launch %><br>
    <%= f.check_box :map_public_ip_on_launch %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aws_subnets/edit.html.erb
<h1>Editing aws_subnet</h1>

<%= render 'form' %>

<%= link_to 'Show', @aws_subnet %> |
<%= link_to 'Back', aws_subnets_path %>

app/views/aws_subnets/index.html.erb
<h1>Listing aws_subnets</h1>

<table class="table table-condensed table-bordered table-hover table-striped">
  <thead>
    <tr>
      <th>Subnet</th>
      <th>State</th>
      <th>Vpc</th>
      <th>Cidr block</th>
      <th>Available ip address count</th>
      <th>Availability zone</th>
      <th>Default for az</th>
      <th>Map public ip on launch</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aws_subnets.each do |aws_subnet| %>
      <tr>
        <td><%= aws_subnet.subnet_id %></td>
        <td><%= aws_subnet.state %></td>
        <td><%= aws_subnet.vpc_id %></td>
        <td><%= aws_subnet.cidr_block %></td>
        <td><%= aws_subnet.available_ip_address_count %></td>
        <td><%= aws_subnet.availability_zone %></td>
        <td><%= aws_subnet.default_for_az %></td>
        <td><%= aws_subnet.map_public_ip_on_launch %></td>
        <td><%= link_to 'Show', aws_subnet %></td>
        <td><%= link_to 'Edit', edit_aws_subnet_path(aws_subnet) %></td>
        <td><%= link_to 'Destroy', aws_subnet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aws subnet', new_aws_subnet_path %>

app/views/aws_subnets/new.html.erb
<h1>New aws_subnet</h1>

<%= render 'form' %>

<%= link_to 'Back', aws_subnets_path %>

app/views/aws_subnets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subnet:</strong>
  <%= @aws_subnet.subnet_id %>
</p>

<p>
  <strong>State:</strong>
  <%= @aws_subnet.state %>
</p>

<p>
  <strong>Vpc:</strong>
  <%= @aws_subnet.vpc_id %>
</p>

<p>
  <strong>Cidr block:</strong>
  <%= @aws_subnet.cidr_block %>
</p>

<p>
  <strong>Available ip address count:</strong>
  <%= @aws_subnet.available_ip_address_count %>
</p>

<p>
  <strong>Availability zone:</strong>
  <%= @aws_subnet.availability_zone %>
</p>

<p>
  <strong>Default for az:</strong>
  <%= @aws_subnet.default_for_az %>
</p>

<p>
  <strong>Map public ip on launch:</strong>
  <%= @aws_subnet.map_public_ip_on_launch %>
</p>

<%= link_to 'Edit', edit_aws_subnet_path(@aws_subnet) %> |
<%= link_to 'Back', aws_subnets_path %>