config/routes.rb
Rails.application.routes.draw do

  get "/hosts/:id/snapshot", to: 'hosts#snapshot', as: 'snapshot'
  get '/hosts/:id/replace_instance', to: 'hosts#replace_instance', as: 'replace'
  get '/hosts/:id/reboot', to: 'hosts#reboot', as: 'reboot'

  resources :instance_security_group_mappings
  resources :aws_security_group_tags
  resources :aws_security_group_ranges
  resources :aws_security_group_pairs
  resources :aws_security_group_egresses
  resources :aws_security_group_ingresses
  resources :aws_security_groups
  resources :aws_route_table_propogates
  resources :aws_route_table_associations
  resources :aws_route_table_tags
  resources :aws_route_table_routes
  resources :aws_route_tables
  resources :aws_network_acl_tags
  resources :aws_network_acl_entries
  resources :aws_network_acls
  resources :aws_key_pairs
  resources :aws_internet_gateway_tags
  resources :aws_internet_gateways
  resources :aws_dhcp_option_attributes
  resources :aws_dhcp_options
  resources :aws_elastic_ips
  resources :aws_account_attributes
  resources :checkpoint_frequencies
  resources :sysids
  resources :ebs_snapshot_tags
  resources :ebs_snapshots
  resources :ebs_volumes
  resources :ebs_volume_tags
  resources :instance_eni_tags
  resources :instance_eni_mappings
  resources :instance_tags
  resources :instance_block_device_mappings
  resources :aws_subnets
  resources :aws_vpc_tags
  resources :aws_vpcs
  resources :instance_enis
  resources :instances
  resources :host_states
  resources :hosts
  resources :aws_azs
  resources :aws_regions
  resources :environments

  resources :aws_accounts

  resources :indices

  root to: 'indices#index', :as => "root"

end

app/models/aws_key_pair.rb
class AwsKeyPair < ActiveRecord::Base
belongs_to :aws_account 
belongs_to :aws_region
has_many :instances, primary_key: "key_name", foreign_key: 'key_name'

def self.update_keys
	AwsAccount.all.each do |account|
		AwsRegion.all.each do |aws_region|
			ec2 = setup_ec2(account.id, aws_region.name)
			kp_array = Array.new
			ec2.describe_key_pairs.key_pairs.each do | kp |
				saved_kp = AwsKeyPair.where(aws_account_id: account.id, aws_region_id: aws_region.id, key_name: kp.key_name).first_or_initialize
				saved_kp.key_fingerprint = kp.key_fingerprint
				saved_kp.save
				kp_array.push kp.key_name
			end
			AwsKeyPair.where(aws_account_id: account.id, aws_region_id: aws_region.id).where.not(key_name: kp_array).delete_all
		end
		
	end
end 




end

app/controllers/aws_key_pairs_controller.rb
class AwsKeyPairsController < ApplicationController
  before_action :set_aws_key_pair, only: [:show, :edit, :update, :destroy]

  # GET /aws_key_pairs
  # GET /aws_key_pairs.json
  def index
    @aws_key_pairs = AwsKeyPair.all
  end

  # GET /aws_key_pairs/1
  # GET /aws_key_pairs/1.json
  def show
  end

  # GET /aws_key_pairs/new
  def new
    @aws_key_pair = AwsKeyPair.new
  end

  # GET /aws_key_pairs/1/edit
  def edit
  end

  # POST /aws_key_pairs
  # POST /aws_key_pairs.json
  def create
    @aws_key_pair = AwsKeyPair.new(aws_key_pair_params)

    respond_to do |format|
      if @aws_key_pair.save
        format.html { redirect_to @aws_key_pair, notice: 'Aws key pair was successfully created.' }
        format.json { render :show, status: :created, location: @aws_key_pair }
      else
        format.html { render :new }
        format.json { render json: @aws_key_pair.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aws_key_pairs/1
  # PATCH/PUT /aws_key_pairs/1.json
  def update
    respond_to do |format|
      if @aws_key_pair.update(aws_key_pair_params)
        format.html { redirect_to @aws_key_pair, notice: 'Aws key pair was successfully updated.' }
        format.json { render :show, status: :ok, location: @aws_key_pair }
      else
        format.html { render :edit }
        format.json { render json: @aws_key_pair.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aws_key_pairs/1
  # DELETE /aws_key_pairs/1.json
  def destroy
    @aws_key_pair.destroy
    respond_to do |format|
      format.html { redirect_to aws_key_pairs_url, notice: 'Aws key pair was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aws_key_pair
      @aws_key_pair = AwsKeyPair.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aws_key_pair_params
      params.require(:aws_key_pair).permit(:aws_account_id, :aws_region_id, :key_name, :key_fingerprint)
    end
end

app/helpers/aws_key_pairs_helper.rb
module AwsKeyPairsHelper
end

app/views/aws_key_pairs/_form.html.erb
<%= form_for(@aws_key_pair) do |f| %>
  <% if @aws_key_pair.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aws_key_pair.errors.count, "error") %> prohibited this aws_key_pair from being saved:</h2>

      <ul>
      <% @aws_key_pair.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :aws_account_id %><br>
    <%= f.number_field :aws_account_id %>
  </div>
  <div class="field">
    <%= f.label :aws_region_id %><br>
    <%= f.number_field :aws_region_id %>
  </div>
  <div class="field">
    <%= f.label :key_name %><br>
    <%= f.text_field :key_name %>
  </div>
  <div class="field">
    <%= f.label :key_fingerprint %><br>
    <%= f.text_field :key_fingerprint %>
  </div>
    <div class="field">
      <%= f.label :key_fingerprint %><br>
      <%= f.text_field :key_fingerprint %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aws_key_pairs/edit.html.erb
<h1>Editing aws_key_pair</h1>

<%= render 'form' %>

<%= link_to 'Show', @aws_key_pair %> |
<%= link_to 'Back', aws_key_pairs_path %>

app/views/aws_key_pairs/index.html.erb
<h1>Listing aws_key_pairs</h1>

<table>
  <thead>
    <tr>
      <th>Aws account</th>
      <th>Aws region</th>
      <th>Key name</th>
      <th>Key fingerprint</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aws_key_pairs.each do |aws_key_pair| %>
      <tr>
        <td><%= aws_key_pair.aws_account_id %></td>
        <td><%= aws_key_pair.aws_region_id %></td>
        <td><%= aws_key_pair.key_name %></td>
        <td><%= aws_key_pair.key_fingerprint %></td>
        <td><%= link_to 'Show', aws_key_pair %></td>
        <td><%= link_to 'Edit', edit_aws_key_pair_path(aws_key_pair) %></td>
        <td><%= link_to 'Destroy', aws_key_pair, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aws key pair', new_aws_key_pair_path %>

app/views/aws_key_pairs/new.html.erb
<h1>New aws_key_pair</h1>

<%= render 'form' %>

<%= link_to 'Back', aws_key_pairs_path %>

app/views/aws_key_pairs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Aws account:</strong>
  <%= @aws_key_pair.aws_account_id %>
</p>

<p>
  <strong>Aws region:</strong>
  <%= @aws_key_pair.aws_region_id %>
</p>

<p>
  <strong>Key name:</strong>
  <%= @aws_key_pair.key_name %>
</p>

<p>
  <strong>Key fingerprint:</strong>
  <%= @aws_key_pair.key_fingerprint %>
</p>

<%= link_to 'Edit', edit_aws_key_pair_path(@aws_key_pair) %> |
<%= link_to 'Back', aws_key_pairs_path %>