config/routes.rb
Rails.application.routes.draw do

  get "/hosts/:id/snapshot", to: 'hosts#snapshot', as: 'snapshot'
  get '/hosts/:id/replace_instance', to: 'hosts#replace_instance', as: 'replace'
  get '/hosts/:id/reboot', to: 'hosts#reboot', as: 'reboot'

  resources :instance_security_group_mappings
  resources :aws_security_group_tags
  resources :aws_security_group_ranges
  resources :aws_security_group_pairs
  resources :aws_security_group_egresses
  resources :aws_security_group_ingresses
  resources :aws_security_groups
  resources :aws_route_table_propogates
  resources :aws_route_table_associations
  resources :aws_route_table_tags
  resources :aws_route_table_routes
  resources :aws_route_tables
  resources :aws_network_acl_tags
  resources :aws_network_acl_entries
  resources :aws_network_acls
  resources :aws_key_pairs
  resources :aws_internet_gateway_tags
  resources :aws_internet_gateways
  resources :aws_dhcp_option_attributes
  resources :aws_dhcp_options
  resources :aws_elastic_ips
  resources :aws_account_attributes
  resources :checkpoint_frequencies
  resources :sysids
  resources :ebs_snapshot_tags
  resources :ebs_snapshots
  resources :ebs_volumes
  resources :ebs_volume_tags
  resources :instance_eni_tags
  resources :instance_eni_mappings
  resources :instance_tags
  resources :instance_block_device_mappings
  resources :aws_subnets
  resources :aws_vpc_tags
  resources :aws_vpcs
  resources :instance_enis
  resources :instances
  resources :host_states
  resources :hosts
  resources :aws_azs
  resources :aws_regions
  resources :environments

  resources :aws_accounts

  resources :indices

  root to: 'indices#index', :as => "root"

end

app/models/instance_block_device_mapping.rb
class InstanceBlockDeviceMapping < ActiveRecord::Base
  belongs_to :instance, primary_key: 'instance_id', foreign_key: 'instance_id'
  belongs_to :ebs_volume, primary_key: 'volume_id', foreign_key: 'volume_id'
  has_many :ebs_snapshots, through: :ebs_volume

  def self.join_all
    self.includes(:ebs_volume,:instance)
  end

end

app/controllers/instance_block_device_mappings_controller.rb
class InstanceBlockDeviceMappingsController < ApplicationController
  before_action :set_instance_block_device_mapping, only: [:show, :edit, :update, :destroy]

  # GET /instance_block_device_mappings
  # GET /instance_block_device_mappings.json
  def index
    @instance_block_device_mappings = InstanceBlockDeviceMapping.all
  end

  # GET /instance_block_device_mappings/1
  # GET /instance_block_device_mappings/1.json
  def show
  end

  # GET /instance_block_device_mappings/new
  def new
    @instance_block_device_mapping = InstanceBlockDeviceMapping.new
  end

  # GET /instance_block_device_mappings/1/edit
  def edit
  end

  # POST /instance_block_device_mappings
  # POST /instance_block_device_mappings.json
  def create
    @instance_block_device_mapping = InstanceBlockDeviceMapping.new(instance_block_device_mapping_params)

    respond_to do |format|
      if @instance_block_device_mapping.save
        format.html { redirect_to @instance_block_device_mapping, notice: 'Instance block device mapping was successfully created.' }
        format.json { render :show, status: :created, location: @instance_block_device_mapping }
      else
        format.html { render :new }
        format.json { render json: @instance_block_device_mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instance_block_device_mappings/1
  # PATCH/PUT /instance_block_device_mappings/1.json
  def update
    respond_to do |format|
      if @instance_block_device_mapping.update(instance_block_device_mapping_params)
        format.html { redirect_to @instance_block_device_mapping, notice: 'Instance block device mapping was successfully updated.' }
        format.json { render :show, status: :ok, location: @instance_block_device_mapping }
      else
        format.html { render :edit }
        format.json { render json: @instance_block_device_mapping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instance_block_device_mappings/1
  # DELETE /instance_block_device_mappings/1.json
  def destroy
    @instance_block_device_mapping.destroy
    respond_to do |format|
      format.html { redirect_to instance_block_device_mappings_url, notice: 'Instance block device mapping was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instance_block_device_mapping
      @instance_block_device_mapping = InstanceBlockDeviceMapping.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instance_block_device_mapping_params
      params.require(:instance_block_device_mapping).permit(:instance_id, :device_name, :volume_id)
    end
end

app/helpers/instance_block_device_mappings_helper.rb
module InstanceBlockDeviceMappingsHelper
end

app/views/instance_block_device_mappings/_form.html.erb
<%= form_for(@instance_block_device_mapping) do |f| %>
  <% if @instance_block_device_mapping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instance_block_device_mapping.errors.count, "error") %> prohibited this instance_block_device_mapping from being saved:</h2>

      <ul>
      <% @instance_block_device_mapping.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :instance_id %><br>
    <%= f.text_field :instance_id %>
  </div>
  <div class="field">
    <%= f.label :device_name %><br>
    <%= f.text_field :device_name %>
  </div>
  <div class="field">
    <%= f.label :volume_id %><br>
    <%= f.text_field :volume_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instance_block_device_mappings/edit.html.erb
<h1>Editing instance_block_device_mapping</h1>

<%= render 'form' %>

<%= link_to 'Show', @instance_block_device_mapping %> |
<%= link_to 'Back', instance_block_device_mappings_path %>

app/views/instance_block_device_mappings/index.html.erb
<h1>Listing instance_block_device_mappings</h1>

<table>
  <thead>
    <tr>
      <th>Instance</th>
      <th>Device name</th>
      <th>Volume</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instance_block_device_mappings.each do |instance_block_device_mapping| %>
      <tr>
        <td><%= instance_block_device_mapping.instance_id %></td>
        <td><%= instance_block_device_mapping.device_name %></td>
        <td><%= instance_block_device_mapping.volume_id %></td>
        <td><%= link_to 'Show', instance_block_device_mapping %></td>
        <td><%= link_to 'Edit', edit_instance_block_device_mapping_path(instance_block_device_mapping) %></td>
        <td><%= link_to 'Destroy', instance_block_device_mapping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instance block device mapping', new_instance_block_device_mapping_path %>

app/views/instance_block_device_mappings/new.html.erb
<h1>New instance_block_device_mapping</h1>

<%= render 'form' %>

<%= link_to 'Back', instance_block_device_mappings_path %>

app/views/instance_block_device_mappings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Instance:</strong>
  <%= @instance_block_device_mapping.instance_id %>
</p>

<p>
  <strong>Device name:</strong>
  <%= @instance_block_device_mapping.device_name %>
</p>

<p>
  <strong>Volume:</strong>
  <%= @instance_block_device_mapping.volume_id %>
</p>

<%= link_to 'Edit', edit_instance_block_device_mapping_path(@instance_block_device_mapping) %> |
<%= link_to 'Back', instance_block_device_mappings_path %>