config/routes.rb
Rails.application.routes.draw do

  get "/hosts/:id/snapshot", to: 'hosts#snapshot', as: 'snapshot'
  get '/hosts/:id/replace_instance', to: 'hosts#replace_instance', as: 'replace'
  get '/hosts/:id/reboot', to: 'hosts#reboot', as: 'reboot'

  resources :instance_security_group_mappings
  resources :aws_security_group_tags
  resources :aws_security_group_ranges
  resources :aws_security_group_pairs
  resources :aws_security_group_egresses
  resources :aws_security_group_ingresses
  resources :aws_security_groups
  resources :aws_route_table_propogates
  resources :aws_route_table_associations
  resources :aws_route_table_tags
  resources :aws_route_table_routes
  resources :aws_route_tables
  resources :aws_network_acl_tags
  resources :aws_network_acl_entries
  resources :aws_network_acls
  resources :aws_key_pairs
  resources :aws_internet_gateway_tags
  resources :aws_internet_gateways
  resources :aws_dhcp_option_attributes
  resources :aws_dhcp_options
  resources :aws_elastic_ips
  resources :aws_account_attributes
  resources :checkpoint_frequencies
  resources :sysids
  resources :ebs_snapshot_tags
  resources :ebs_snapshots
  resources :ebs_volumes
  resources :ebs_volume_tags
  resources :instance_eni_tags
  resources :instance_eni_mappings
  resources :instance_tags
  resources :instance_block_device_mappings
  resources :aws_subnets
  resources :aws_vpc_tags
  resources :aws_vpcs
  resources :instance_enis
  resources :instances
  resources :host_states
  resources :hosts
  resources :aws_azs
  resources :aws_regions
  resources :environments

  resources :aws_accounts

  resources :indices

  root to: 'indices#index', :as => "root"

end

app/models/aws_internet_gateway.rb
class AwsInternetGateway < ActiveRecord::Base
belongs_to :aws_account
belongs_to :aws_region 

def self.update_gw
		AwsAccount.all.each do |account|
			AwsRegion.all.each do |aws_region|
				ec2 = setup_ec2(account.id, aws_region.name)
				gw_array = Array.new
				ec2.describe_internet_gateways.internet_gateways.each do | gw |
					saved_gw = AwsInternetGateway.where(aws_account_id: account.id, aws_region_id: aws_region.id, internet_gateway_id: gw.internet_gateway_id ).first_or_initialize
					saved_gw.attachment_vpc_id = gw.attachments[0].vpc_id
					saved_gw.attachment_state = gw.attachments[0].state
					saved_gw.save
					gw_array.push gw.internet_gateway_id
					#
					# Update TAGS
					tag_array = Array.new
					gw.tags do |tag|
						save_tag = AwsInternetGatewayTag.where(internet_gateway_id: gw.internet_gateway_id, key: tag.key).first_or_initialize
						save_tag.value = tag.value
						save_tag.save
						tag_array.push tag.key
					end
					AwsInternetGatewayTag.where(internet_gateway_id: gw.internet_gateway_id).where.not(key: tag_array).delete_all
				end
				AwsInternetGateway.where(aws_account_id: account.id, aws_region_id: aws_region.id).where.not(internet_gateway_id: gw_array).delete_all
			end
			
		end
	end 



end

app/controllers/aws_internet_gateways_controller.rb
class AwsInternetGatewaysController < ApplicationController
  before_action :set_aws_internet_gateway, only: [:show, :edit, :update, :destroy]

  # GET /aws_internet_gateways
  # GET /aws_internet_gateways.json
  def index
    @aws_internet_gateways = AwsInternetGateway.all
  end

  # GET /aws_internet_gateways/1
  # GET /aws_internet_gateways/1.json
  def show
  end

  # GET /aws_internet_gateways/new
  def new
    @aws_internet_gateway = AwsInternetGateway.new
  end

  # GET /aws_internet_gateways/1/edit
  def edit
  end

  # POST /aws_internet_gateways
  # POST /aws_internet_gateways.json
  def create
    @aws_internet_gateway = AwsInternetGateway.new(aws_internet_gateway_params)

    respond_to do |format|
      if @aws_internet_gateway.save
        format.html { redirect_to @aws_internet_gateway, notice: 'Aws internet gateway was successfully created.' }
        format.json { render :show, status: :created, location: @aws_internet_gateway }
      else
        format.html { render :new }
        format.json { render json: @aws_internet_gateway.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aws_internet_gateways/1
  # PATCH/PUT /aws_internet_gateways/1.json
  def update
    respond_to do |format|
      if @aws_internet_gateway.update(aws_internet_gateway_params)
        format.html { redirect_to @aws_internet_gateway, notice: 'Aws internet gateway was successfully updated.' }
        format.json { render :show, status: :ok, location: @aws_internet_gateway }
      else
        format.html { render :edit }
        format.json { render json: @aws_internet_gateway.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aws_internet_gateways/1
  # DELETE /aws_internet_gateways/1.json
  def destroy
    @aws_internet_gateway.destroy
    respond_to do |format|
      format.html { redirect_to aws_internet_gateways_url, notice: 'Aws internet gateway was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aws_internet_gateway
      @aws_internet_gateway = AwsInternetGateway.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aws_internet_gateway_params
      params.require(:aws_internet_gateway).permit(:aws_account_id, :aws_region_id, :internet_gateway_id, :attachment_vpc_id, :attachment_state)
    end
end

app/helpers/aws_internet_gateways_helper.rb
module AwsInternetGatewaysHelper
end

app/views/aws_internet_gateways/_form.html.erb
<%= form_for(@aws_internet_gateway) do |f| %>
  <% if @aws_internet_gateway.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aws_internet_gateway.errors.count, "error") %> prohibited this aws_internet_gateway from being saved:</h2>

      <ul>
      <% @aws_internet_gateway.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :aws_account_id %><br>
    <%= f.number_field :aws_account_id %>
  </div>
  <div class="field">
    <%= f.label :aws_region_id %><br>
    <%= f.number_field :aws_region_id %>
  </div>
  <div class="field">
    <%= f.label :internet_gateway_id %><br>
    <%= f.text_field :internet_gateway_id %>
  </div>
  <div class="field">
    <%= f.label :attachment_vpc_id %><br>
    <%= f.text_field :attachment_vpc_id %>
  </div>
  <div class="field">
    <%= f.label :attachment_state %><br>
    <%= f.text_field :attachment_state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aws_internet_gateways/edit.html.erb
<h1>Editing aws_internet_gateway</h1>

<%= render 'form' %>

<%= link_to 'Show', @aws_internet_gateway %> |
<%= link_to 'Back', aws_internet_gateways_path %>

app/views/aws_internet_gateways/index.html.erb
<h1>Listing aws_internet_gateways</h1>

<table>
  <thead>
    <tr>
      <th>Aws account</th>
      <th>Aws region</th>
      <th>Internet gateway</th>
      <th>Attachment vpc</th>
      <th>Attachment state</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aws_internet_gateways.each do |aws_internet_gateway| %>
      <tr>
        <td><%= aws_internet_gateway.aws_account_id %></td>
        <td><%= aws_internet_gateway.aws_region_id %></td>
        <td><%= aws_internet_gateway.internet_gateway_id %></td>
        <td><%= aws_internet_gateway.attachment_vpc_id %></td>
        <td><%= aws_internet_gateway.attachment_state %></td>
        <td><%= link_to 'Show', aws_internet_gateway %></td>
        <td><%= link_to 'Edit', edit_aws_internet_gateway_path(aws_internet_gateway) %></td>
        <td><%= link_to 'Destroy', aws_internet_gateway, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aws internet gateway', new_aws_internet_gateway_path %>

app/views/aws_internet_gateways/new.html.erb
<h1>New aws_internet_gateway</h1>

<%= render 'form' %>

<%= link_to 'Back', aws_internet_gateways_path %>

app/views/aws_internet_gateways/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Aws account:</strong>
  <%= @aws_internet_gateway.aws_account_id %>
</p>

<p>
  <strong>Aws region:</strong>
  <%= @aws_internet_gateway.aws_region_id %>
</p>

<p>
  <strong>Internet gateway:</strong>
  <%= @aws_internet_gateway.internet_gateway_id %>
</p>

<p>
  <strong>Attachment vpc:</strong>
  <%= @aws_internet_gateway.attachment_vpc_id %>
</p>

<p>
  <strong>Attachment state:</strong>
  <%= @aws_internet_gateway.attachment_state %>
</p>

<%= link_to 'Edit', edit_aws_internet_gateway_path(@aws_internet_gateway) %> |
<%= link_to 'Back', aws_internet_gateways_path %>